### ISSUE TITLE
Markdown processing does not support lists

### ISSUE THREAD

**Issue by Ttech** [Naereen/Nginx-Fancyindex-Theme#12]
The Markdown processing doesn't appear to properly handle lists and a lot of standard markdown formatting leaving a large blob of text.

**Comment by Naereen** [comment]
Hi,
It's quite surprising, I never found any bug in my tests.
Could you please show a screenshot of the bugs (and maybe attach a sample README.md or HEADER.md file that leads to the bug)?
Thanks in advance.

**Comment by Ttech** [comment]
Here's a screenshot
https://imgur.com/a/myIA9zu
Anything with bullets or any formatting really it seems. I've used other md editors to verify it looks as expected.

**Comment by Naereen** [comment]
That's odd. Let me do some tests and I would come back to you. (in a few days, it's holiday here in France!)

**Comment by Naereen** [comment]
OK it's very weird, nothing works correctly but my tests were all fine.

**Comment by Naereen** [comment]
Could you download the latest version and try again please?

**Comment by Ttech** [comment]
Thank you! You fixed it!

**Comment by Naereen** [comment]
Great! Glad I managed to do it.
Please don't hesitate to create new issues if needed.
Farewell!
