### ISSUE TITLE
Odd styling

### ISSUE THREAD

**Issue by nfugal** [Naereen/Nginx-Fancyindex-Theme#14]
Hi,

I'm probably missing something simple, but when I try to use your theme, the results are a bit odd
.
If I leave the references to the header and footer in my nginix.conf, no styling is applied to the index at all.
If I remove the references to header and footer, the styling is off, but there. See the screenshot I included.

![2018-05-27_02 32 38](https://user-images.githubusercontent.com/10454053/40583984-5309971a-6156-11e8-8e0a-9d8a61aa3bff.png)
The blank looking lines are files that should be listed.

Again, I'm not sure if this is a bug or if I missed something. 

Thanks for sharing your work!

**Comment by Naereen** [comment]
Hi,
Thanks for reporting this.
I'm not sure what can go wrong here...

Have you copied the theme folder (light or dark) to the root folder of your local website?

**Comment by nfugal** [comment]
It goes in the site root? I thought in the root of a directory to be auto/fancy indexed. Perhaps that's my issue.

**Comment by Naereen** [comment]
Yes, see [the installation instruction](https://github.com/Naereen/Nginx-Fancyindex-Theme#usage).
> Move the `Nginx-Fancyindex-Theme/` folder to the root of the site directory.

But you could change this, by changing links in all the html and conf files from `/Nginx-Fancyindex-Theme/` to `Nginx-Fancyindex-Theme/` (note the leading `/` which is removed, to specify that the folder should be searched for inside the current directory, and not at the website root)

**Comment by Naereen** [comment]
Hi again,
No sorry I don't see what could happen here…

Are you sure you included all the files from the [theme](https://github.com/Naereen/Nginx-Fancyindex-Theme/tree/master/Nginx-Fancyindex-Theme-light) folder?

I don't know of any issue in using docker and my theme, but again I didn't (and won't) test it myself, so maybe something fishy is going on.

**Comment by psycholyzern** [comment]
There are 2 possible fixes.

1. Move `Nginx-Fancyindex-Theme-light` to your root dir, not `Nginx-Fancyindex-Theme`.

or

2. Follow the exact steps under [Usage](https://github.com/Naereen/Nginx-Fancyindex-Theme/blob/master/README.md#usage), but edit path `Nginx-Fancyindex-Theme` to `Nginx-Fancyindex-Theme/Nginx-Fancyindex-Theme-light` in nginx configuration, header.html and footer.html

**Comment by psycholyzern** [comment]
@Naereen the Usage tutorial ask user to put `Nginx-Fancyindex-Theme` in the root dir, but configuration, header.html and footer.html are written to serve `Nginx-Fancyindex-Theme-light`.

The tutorial should tell us to move `Nginx-Fancyindex-Theme-light` and `Nginx-Fancyindex-Theme-dark` to root dir, not move the parent folder `Nginx-Fancyindex-Theme`.

**Comment by Naereen** [comment]
Hi @psycholyzern, thanks for the precision, I will update the README.md accordingly.
(this whole distinction between light and dark theme was done recently, I forgot to update everything)

**Comment by Naereen** [comment]
@nfugal please tell us if the details given by @psycholyzern were sufficient to solve your problem? (I'll then close this)

**Comment by Naereen** [comment]
Haven't heard from you in the last month, I assume this issue is solved.
