### ISSUE TITLE
fancyindex-can-t-print-list-with-auth-ldap-module

### ISSUE THREAD

**Issue by duanzhanling** [Naereen/Nginx-Fancyindex-Theme#15]
https://www.bountysource.com/issues/56084981-fancyindex-can-t-print-list-with-auth-ldap-module

ldap_server ldap.domain.com {
    url ldaps://ldap.domain.com/OU=People,DC=domain,DC=com?uid?sub?(objectClass=posixAccount);
    binddn "uid=ssomanager,ou=admin,dc=domain,dc=com";
    binddn_passwd acblfebadiced@T;
    group_attribute uniquemember;
    group_attribute_is_dn on;
    require valid_user;

    ssl_check_cert off;
    satisfy any;
}

server {
   listen        80 default_server backlog=1024;
   server_name   _;

    auth_ldap "Forbidden";
    auth_ldap_servers ldap.domain.com;

    ..blah..blah

    location / {
        if ( $http_user_agent ~* "bot" ) {
            access_log off;
        }

        if ( $request_filename ~* "\.(js|css|png|jpg|jpeg|gif|ico)$" ) {
            access_log off;
        }

        fancyindex on;
        fancyindex_localtime on;
        fancyindex_exact_size off;
        fancyindex_header "/fancyindex/header.html";
        fancyindex_footer "/fancyindex/footer.html";
    }

}

**Comment by Naereen** [comment]
Hello?
What do you want from me? I don't really understand the purpose of this issue, please explain.
Regards :smiley:!

**Comment by duanzhanling** [comment]
it is OK to combine nginx and openldap auth function.
but web could not be opened when enable fancyindex theme

**Comment by duanzhanling** [comment]
@Naereen do you understand ？

**Comment by Naereen** [comment]
OK. But this bug concerns openldap and fancyindex only right, I'm not sure what I could change from the theme side to fix it…

**Comment by duanzhanling** [comment]
Oh, tks

**Comment by duanzhanling** [comment]
@Naereen I guess it has been solved。
https://github.com/Joungkyun/ngx-fancyindex/commit/7373c077d659d1e39524e47beb8f25bd8349f0f7

**Comment by Naereen** [comment]
OK. So as I said, this had nothing to do with my theme, right?
Thanks for reporting it anyway.
(closing)
