### ISSUE TITLE
Please Add the support of Nginx 1.14.x feature

### ISSUE THREAD

**Issue by kongfanhe303690396** [Naereen/Nginx-Fancyindex-Theme#16]
Please Add the support of Nginx 1.14.x feature

**Comment by Naereen** [comment]
Hi.
What do you want exactly, could you please be more precise?
What changed on nginx at 1.14x?

**Comment by kongfanhe303690396** [comment]
Sorry, I said fancyindex version, my nginx version is 1.14.x, can not install fancyindex

**Comment by Naereen** [comment]
I don't know, please see the documentation of fancyindex, https://github.com/aperezdc/ngx-fancyindex#building
