### ISSUE TITLE
在页面的头部和尾部显示404，找不到主题

### ISSUE THREAD

**Issue by feiyx** [Naereen/Nginx-Fancyindex-Theme#17]
在页面的头部和尾部显示404，找不到主题

**Comment by feiyx** [comment]
问题已解决。

**Comment by feiyx** [comment]
问题为：在主题的配置文件中少了一层目录，https://segmentfault.com/a/1190000012606305
解决方案：使用新的主题了，地址如下：https://github.com/lanffy/Nginx-Fancyindex-Theme

**Comment by Naereen** [comment]
I don't speak Chinese, please close this issue and open a new one in English (or French), sorry.
