### ISSUE TITLE
404 requests for HEADER.md README.md per directory

### ISSUE THREAD

**Issue by jtmoon79** [Naereen/Nginx-Fancyindex-Theme#18]
Great theme.  Thanks for sharing it!

Each request made to a directory also makes a request for `README.md` and `HEADER.md`.  Both return a _404_.

**Comment by Naereen** [comment]
Hi @jtmoon79,
That's not a bug, it's a feature: see https://github.com/Naereen/Nginx-Fancyindex-Theme#include-header-and-readme-files-automatically
