### ISSUE TITLE
Populate README to subdirectories

### ISSUE THREAD

**Issue by pat-s** [Naereen/Nginx-Fancyindex-Theme#19]
Is this possible? I would like to have the same header from the site root populate to all subdirs. 

The README contains the impressum which should apply on all pages. I would like to avoid creating redundant files or stating this explicit in the README.

**Comment by Naereen** [comment]
Hi,
It's interesting, but I think such manipulation should be done from the server side (e.g., Apache HTTPD or NGinx), not from the javascript front-end of this Fancyindex-Theme.
I don't have time to try myself what you ask, sorry.
If you come up with an elegant working solution, I will gladly integrate it in this project and document it!

**Comment by pat-s** [comment]
Ok, thanks for the quick reply. I neither have time nor the skills to do this atm.
