### ISSUE TITLE
question about HEADER.md and README.md

### ISSUE THREAD

**Issue by e71828** [Naereen/Nginx-Fancyindex-Theme#20]
Hi,
As what you said in the usage, A new feature is the automatic inclusion of HEADER.md and README.md file from the current directory (if any), but  I cannot  get the effects automaticaly, no header and readme? 

How could I get this feature? like here, https://github.com/Naereen/Nginx-Fancyindex-Theme#include-header-and-readme-files-automatically

**Comment by Naereen** [comment]
Hi @e71828.
- Have you updated the software to the most recent version? You should follow again the instructions for installing it,
- Have you checked that there are a `README.md` and a `HEADER.md` file in the directory served by nginx and displayed by FancyIndex with the Nginx-FancyIndex-Theme theme ?
- If they are indeed present, but not displayed, check the permissions, maybe they are only readable by you and not any other user/group (I think I remember that nginx runs by default on a user named `www-data`, maybe this user does not have access to the two files on your laptop)

Maybe you can also try to open the network debugging tool of your browser (Firefox : Menu : Web development : Network, or Ctrl+Maj+E, Google Chrome/Chromium, see https://developers.google.com/web/tools/chrome-devtools/network/).
And by relaunching the webpage served by nginx, you should see if the javascript code tries to load/read the two HEADER/README.md file, and maybe the network debugging tool will tell you the nature of the issue (file missing, not readable, etc).

**Comment by e71828** [comment]
![image](https://user-images.githubusercontent.com/24602820/63528109-ec9a0980-c534-11e9-9f2e-fd062493b330.png)
OK，thank you！

by checking  with F12 in chrome, I found  the problem.

**Comment by e71828** [comment]
then  I wonder，how can I apply this on all pages？ I am a freshman， I think may  should  specify a file location for the two files。

**Comment by Naereen** [comment]
Good!
You can apply this on all pages by having a HEADER/README file in all directories and sub-directories.
I haven't found a way to do this automatically (see #19).
