### ISSUE TITLE
Search does not work with unicode chars

### ISSUE THREAD

**Issue by sgf-dma** [Naereen/Nginx-Fancyindex-Theme#22]
Hi.

JS search does not work with unicode chars. It seems, the reason is '\b' in regexp (just because it does not match on boundaries of unicode words). As far as i can tell, there're at least two ways to fix it:
1. Do not use '\b'.
2. Use[XRegExp](http://xregexp.com/), then we may try to reimplement '\b' using ['\p{L}'](http://xregexp.com/plugins/).

May be something else is possible, but i don't really know JS, so these are the first, which come from google.

**Comment by Naereen** [comment]
Hi @sgf-dma,
Thanks for pointing this out. I will try to fix the issue.

**Comment by sgf-dma** [comment]
Here're variants i've tried. All of them seems to work, but use xregexp. In footer.html i've added:

    <script src="https://unpkg.com/xregexp/xregexp-all.js"></script>

then variable `e` from `input.addEventListener()` in `addNginxFancyIndexForm.js` may be defined as

        // Word sequence _matching_ to input. All, except last, words must be _complete_.
        e = "(^|.*[^\\pL])" + this.value.trim().split(/\s+/).join("([^\\pL]|[^\\pL].*[^\\pL])") + ".*$",

or

        // Word sequence may be any, but all, except last, words must be _complete_.
        e = "^(?=(.*[^\\pL])?" + this.value.trim().split(/\s+/).join("[^\\pL])(?=.*[^\\pL]") + ").*$",

or

        // Word sequence may be any, all words may be incomplete.
        e = "^(?=(.*[^\\pL])?" + this.value.trim().split(/\s+/).join(")(?=.*[^\\pL]") + ").*$",

**Comment by Naereen** [comment]
Thanks, I've used the first solution.
I don't have a proper installation of nginx on my laptop (yet), I'll try to test it soon.
