### ISSUE TITLE
Add note about upcoming removal of fancyindex_name_length

### ISSUE THREAD

**Issue by ryandesign** [Naereen/Nginx-Fancyindex-Theme#27]
The readme suggests using `fancyindex_name_length` and says you may encounter an error if using an old version of fancyindex and should comment it out. In fact, you will also encounter an error with the latest not-yet-released version of fancyindex, since `fancyindex_name_length` has been removed. See https://github.com/aperezdc/ngx-fancyindex/commit/5930c29d6a97787c101cee63b62f6eaa2945bd96. You may want to amend that comment to account for this impending breaking change.

**Comment by Naereen** [comment]
Hi @ryandesign,
Thanks, I remove this line entirely, it never was useful.
Regards.
