### ISSUE TITLE
这个项目作者还在吗

### ISSUE THREAD

**Issue by sudocodus** [Naereen/Nginx-Fancyindex-Theme#29]
有个问题咨询

**Comment by Naereen** [comment]
Hello @sudocodus,
Please write in English, I'm not fluent in Chinese. (I used Google Translate)
Yes, I am still alive, but this project is no longer actively maintained.
Do you have a question?
Regards.

**Comment by sudocodus** [comment]
> 
@Naereen 
Hello, thank you for your reply, you did this project is very useful, I used it in the storage and retrieval of my own data, the only regret is that it does not have a pagination function for too much data, I am not familiar with JS scripts, hope to improve it, I don't know if you have time to add this function, each paging shows how many entries as configuration items can be configured, if it can be achieved it is perfect. If you don't add any more features, thank you for your contribution.

**Comment by Naereen** [comment]
Hello,
Thank you for your reply.
I don't have the skills to add the requested feature, sorry.
Kind regards from France.

Le 14 juin 2023 09:02:17 GMT+02:00, yyyeeesss ***@***.***> a écrit :
>> 
>@Naereen 
>Hello, thank you for your reply, you did this project is very useful, I used it in the storage and retrieval of my own data, the only regret is that it does not have a pagination function for too much data, I am not familiar with JS scripts, hope to improve it, I don't know if you have time to add this function, each paging shows how many entries as configuration items can be configured, if it can be achieved it is perfect. If you don't add any more features, thank you for your contribution.
>

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by sudocodus** [comment]
> 

@Naereen 
Are you the author of this project

**Comment by Naereen** [comment]
I think I initially forked it from someone, who later deleted his/her project so mine got the attention instead. I worked on it a little bit, but not enough to be able to add features.
I'll close this issue now. Bye :-)
