### ISSUE TITLE
toggle between light and dark mode

### ISSUE THREAD

**Issue by oscni** [Naereen/Nginx-Fancyindex-Theme#30]
add button for user to be able to toggle between light and dark mode :)

**Comment by Naereen** [comment]
Hi there @oscni,
That's an interesting suggestion.
Unfortunately, I no longer maintain this project. I don't have time to do that.

If you are interested on a personal level to have the ability to switch between light & dark modes, there is the very great DarkReader (https://darkreader.org/) extension for Firefox and Chrom(e/ium).

Regards
