### ISSUE TITLE
Changing white background

### ISSUE THREAD

**Issue by betawi** [Naereen/Nginx-Fancyindex-Theme#6]
Sorry if this sound newbiesh
but i want to change white background to an image.
i try adding this code in header.html

```
<head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="IE=edge">
        <title>Topkek</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/Nginx-Fancyindex-Theme/styles.css">
<style>
body {
        overflow-y: hidden ! important;
        overflow-x: hidden ! important;
        background-color: #f8f8f8;
        background-image: url('bg.jpg');
        /*background-size: cover;*/
        background-size: contain;
        background-repeat: no-repeat;
        background-position: right;
}
</style>
    </head>
```

But it seems not changing,
Any ideas?

**Comment by betawi** [comment]
I also tried with style.css
```

body {
    margin: 0 auto;
    padding-top: 20px;
    max-width: 800px;
    background-image: url("bg2.png");
}
```

still no effect

**Comment by Naereen** [comment]
Hi,
Sorry for the delay.

Where is stored your image?
You can see in the `header.html` file that files related to Nginx-Fancyindex-Theme are *assumed* to be stored on the server root-level under absolute path `/Nginx-Fancyindex-Theme/` (for instance, on Apache HTTPD, if your webserver root is `/var/www/html/` then put the content of the `Nginx-Fancyindex-Theme/` folder from this project to `/var/www/html/Nginx-Fancyindex-Theme/`).
Your image `"bg.png"` or `"bg2.png"` must be in this folder.

For your first try, I think you should not use a `background-color` and a `background-image` attribute, but only one. ([More details](https://www.w3schools.com/css/css_background.asp))
